#!/usr/bin/env bash
#nesting if statements
if -f School
then
	echo "school file exists"
	if -s School	
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
else
then
	echo "school file does not exist"
fi
