#!/usr/bin/env bash
if -f school
then
	echo "school file is a regular file"
	echo "school file exists"
	if -s school	
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
else
then
	echo "school file does not exist"
fi
