#!/usr/bin/env bash
# nesting if statements
if [ -f school ]; then
	if [ -s school ];	
	then
		echo 'school file exists'
		echo "school file is not empty"
	else
		echo "school file exists"
		echo "school file is empty"
	fi
	echo "school is a regular file"
elif [ -d school ];
then
	if [ -s school ];
		then
                echo 'school file exists'
                echo "school file is not empty"
        else
                echo "school file exists"
                echo "school file is empty"
        fi
        echo "school is a regular file"
else
	echo "school file does not exist"
fi
